# Generated by Django 5.0.6 on 2024-06-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosFuncionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcionario', models.TextField(max_length=255)),
                ('idade_funcionario', models.IntegerField()),
                ('telefone_funcionario', models.TextField(max_length=11)),
            ],
        ),
    ]
