# Generated by Django 5.0.6 on 2024-06-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva', models.IntegerField()),
                ('nome_cliente', models.TextField(max_length=255)),
                ('telefone_cliente', models.TextField(max_length=11)),
                ('email_cliente', models.TextField(max_length=150)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('numero_pessoas', models.IntegerField()),
                ('ocasiao_especial', models.BooleanField()),
                ('comentarios', models.TextField(max_length=1000)),
            ],
        ),
    ]
