# Generated by Django 5.0.6 on 2024-06-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_remove_reserva_id_alter_reserva_id_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='ocasiao_especial',
            field=models.TextField(max_length=30),
        ),
    ]
